spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: elo
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    default-schema: biblioteca
    change-log: classpath:/db/master.xml
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mySecretToken: ${ALGORITHM_SECRET_TOKEN}

createDatabaseIfNotExist: true

server:
  port: 8080
