spring:
    server: 8080
    datasource:
      url: jdbc:postgresql://db-biblioteca.c78aq4siyt49.sa-east-1.rds.amazonaws.com:5432/
      username: postgres
      password: biblioteca123
    driver-class-name=org:
      postgresql:
        Driver:jpa:
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    liquibase:
      enabled: true
      default-schema: biblioteca
      change-log: classpath:/db/master.xml
    mail:
      host: ${MAIL_HOST}
      port: ${MAIL_PORT}
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

createDatabaseIfNotExist: true

mySecretToken: ${ALGORITHM_SECRET_TOKEN}
